make:
	make build
	make run
	make clean

build:
	echo Building...
	gcc bubble_sort.c

run:
	echo Running...
	java BubbleSort.java
	python ./bubble-sort.py
	./a.out

clean: 
	echo Cleaning...
	rm a.out

