make:
	make build
	make run
	make clean

build:
	echo Building...
	gcc hello_world.c

run:
	echo Running...
	java HelloWorld.java
	python ./hello-world.py
	./a.out

clean: 
	echo Cleaning...
	rm a.out

